/**
 * Renders consistent food photography for every curated recipe using Gemini
 * image generation, then rewrites src/data/recipeArt.ts so the app bundles it.
 *
 *   GEMINI_API_KEY=AIza... npm run generate:art          # fill in missing art
 *   GEMINI_API_KEY=AIza... npm run generate:art -- --force   # re-render all
 *
 * Cost: ~$0.04/image · 16 recipes ≈ 100+ images ≈ $4–5 one-time.
 * The script is resumable — it skips images that already exist on disk.
 */
import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RECIPES } from '../src/data/recipes';
import type { Recipe, RecipeStep } from '../src/types';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(ROOT, 'assets', 'recipes');
const ART_TS = join(ROOT, 'src', 'data', 'recipeArt.ts');

const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = process.env.GEMINI_IMAGE_MODEL ?? 'gemini-2.5-flash-image';
const FORCE = process.argv.includes('--force');

if (!API_KEY) {
  console.error('Set GEMINI_API_KEY first: GEMINI_API_KEY=AIza... npm run generate:art');
  process.exit(1);
}

// One art direction for the whole library — every image looks like it came
// from the same home kitchen, same phone, same afternoon.
const STYLE = `Photorealistic photo shot on an iPhone in a real lived-in home kitchen.
Natural daylight from a window on the left, soft shadows, warm honest tones, slight grain.
Shallow depth of field, casual 45-degree angle (not perfectly styled, not stock-photo flat-lay).
Matte wooden countertop, a rumpled cream linen towel nearby, well-used cookware.
Absolutely no text, no watermark, no people's faces, no studio lighting, no plastic-looking food.`;

function coverPrompt(r: Recipe): string {
  return `${STYLE}
The finished dish: ${r.title} — ${r.tagline}. ${r.cuisine} cooking, plated simply and appetizingly on ceramic, just served, steam still rising.`;
}

function stepPrompt(r: Recipe, s: RecipeStep): string {
  return `${STYLE}
A moment mid-recipe while cooking ${r.title}. This exact stage: ${s.title} — ${s.instruction}
What the food looks like right now: ${s.visualCue ?? s.instruction}. Show the food/pan/board only, hands allowed if natural.`;
}

async function renderImage(prompt: string): Promise<Buffer> {
  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-goog-api-key': API_KEY! },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { imageConfig: { aspectRatio: '4:3' } },
      }),
    },
  );
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data = (await res.json()) as {
    candidates?: { content?: { parts?: { inlineData?: { data?: string } }[] } }[];
  };
  const b64 = data.candidates?.[0]?.content?.parts?.find((p) => p.inlineData?.data)?.inlineData?.data;
  if (!b64) throw new Error('no image in response');
  return Buffer.from(b64, 'base64');
}

async function renderTo(file: string, prompt: string, label: string): Promise<boolean> {
  if (existsSync(file) && !FORCE) {
    console.log(`  ⏭  ${label} (exists)`);
    return true;
  }
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const img = await renderImage(prompt);
      writeFileSync(file, img);
      console.log(`  ✅ ${label}`);
      return true;
    } catch (err) {
      console.warn(`  ⚠️  ${label} attempt ${attempt}: ${(err as Error).message.slice(0, 140)}`);
      await new Promise((r) => setTimeout(r, 2500 * attempt));
    }
  }
  return false;
}

function writeArtMap() {
  let body = `// AUTO-GENERATED by scripts/generate-recipe-art.ts — do not edit by hand.
// Re-run \`npm run generate:art\` after adding recipes.

export type ArtSource = number | { uri: string };

export interface RecipeArt {
  cover?: ArtSource;
  steps: Record<string, ArtSource>;
}

export const RECIPE_ART: Record<string, RecipeArt> = {
`;
  for (const r of RECIPES) {
    const dir = join(ASSETS, r.id);
    const coverFile = join(dir, 'cover.jpg');
    const stepEntries = r.steps
      .filter((s) => existsSync(join(dir, `step_${s.id}.jpg`)))
      .map((s) => `      ${JSON.stringify(s.id)}: require('../../assets/recipes/${r.id}/step_${s.id}.jpg'),`)
      .join('\n');
    const hasCover = existsSync(coverFile);
    if (!hasCover && !stepEntries) continue;
    body += `  ${JSON.stringify(r.id)}: {\n`;
    if (hasCover) body += `    cover: require('../../assets/recipes/${r.id}/cover.jpg'),\n`;
    body += `    steps: {\n${stepEntries}\n    },\n  },\n`;
  }
  body += `};

export function getArt(recipeId: string): RecipeArt | undefined {
  return RECIPE_ART[recipeId];
}
`;
  writeFileSync(ART_TS, body);
  console.log(`\n📝 wrote ${ART_TS}`);
}

async function main() {
  console.log(`🎨 Rendering recipe art with ${MODEL} (${RECIPES.length} recipes)\n`);
  for (const r of RECIPES) {
    console.log(`\n${r.emoji} ${r.title}`);
    const dir = join(ASSETS, r.id);
    mkdirSync(dir, { recursive: true });
    await renderTo(join(dir, 'cover.jpg'), coverPrompt(r), 'cover');
    for (const s of r.steps) {
      await renderTo(join(dir, `step_${s.id}.jpg`), stepPrompt(r, s), `step ${s.id}: ${s.title}`);
    }
  }
  writeArtMap();
  console.log('\nDone. Commit assets/recipes/ and src/data/recipeArt.ts, then redeploy.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
